apiVersion: v2
name: catalog
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 9.8.2    # check latest compatible version
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 19.10.1
    repository: https://charts.bitnami.com/bitnami
