apiVersion: v2
name: catalog
version: 0.1.0
appVersion: "1.0.0"


dependencies:
  - name: mysql
    version: 9.23.0
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 19.6.0
    repository: https://charts.bitnami.com/bitnami