image:
  repository: chiruapala/catalog-service
  tag: 1.0.0

service:
  port: 8081


mysql:
  image:
    registry: docker.io
    repository: mysql
    tag: "8.0.36"
  fullnameOverride: "mysql"
  auth:
    rootPassword: root
    database: catalogdb
    username: cataloguser
    password: catalogpassword

  primary:
    persistence:
      enabled: false   # OK for local/dev

redis:
  image:
    registry: docker.io
    repository: redis
    tag: "7.0"
  fullnameOverride: "redis"
  architecture: standalone
  auth:
    enabled: false